In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
train=pd.read_csv(r"F:\ML_dataset\set_2\train.csv")
test=pd.read_csv(r"F:\ML_dataset\set_2\test.csv")

In [3]:
print(train.shape)
print(test.shape)

(1213, 12)
(1211, 11)


In [4]:
train.head(10)

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0     Owner                 0.0   0.0      2.0       BHK  1300.236407   
1    Dealer                 0.0   0.0      2.0       BHK  1275.000000   
2     Owner                 0.0   0.0      2.0       BHK   933.159722   
3     Owner                 0.0   1.0      2.0       BHK   929.921143   
4    Dealer                 1.0   0.0      2.0       BHK   999.009247   
5     Owner                 0.0   0.0      3.0       BHK          NaN   
6    Dealer                 0.0   0.0      3.0       BHK  1495.053957   
7     Owner                 0.0   1.0      3.0       BHK  1181.012946   
8    Dealer                 0.0   1.0      2.0       BHK  1040.000000   
9     Owner                 0.0   1.0      2.0       BHK   879.120879   

   READY_TO_MOVE  RESALE ADDRESS  LONGITUDE   LATITUDE  TARGET(PRICE_IN_LACS)  
0            1.0       1     NaN  12.969910  77.597960                   55.0  
1            1.0       1     NaN  12.274538  76.644605                   51.0  
2            1.0       1     NaN  12.778033  77.632191                   43.0  
3            1.0       1     NaN  28.642300  77.344500                   62.5  
4            0.0       1     NaN  22.592200  88.484911                   60.5  
5            1.0       1     NaN  10.033280  76.282571                   42.0  
6            1.0       1     NaN  26.916347  75.795600                   66.5  
7            1.0       1     NaN  30.740000  76.650000                   52.0  
8            1.0       1     NaN  13.054202  77.674002                   41.6  
9            1.0       1     NaN  12.951610  80.140970                   36.0

In [5]:
test.head(10)

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0     Owner                   0     0        1       BHK   545.171340   
1    Dealer                   1     1        2       BHK   800.000000   
2    Dealer                   0     0        2       BHK  1257.096513   
3    Dealer                   0     0        3       BHK  1400.329489   
4     Owner                   0     0        1       BHK   430.477830   
5     Owner                   0     0        2       BHK   500.000000   
6    Dealer                   0     0        1       BHK   724.835886   
7    Dealer                   1     1        1       BHK   778.842862   
8    Dealer                   0     0        1       BHK   600.055819   
9    Dealer                   0     0        2       BHK  1323.591698   

   READY_TO_MOVE  RESALE                   ADDRESS  LONGITUDE   LATITUDE  
0              1       1              Kamrej,Surat  21.262000  73.047700  
1              0       0           Panvel,Lalitpur  18.966114  73.148278  
2              1       1          New Town,Kolkata  22.592200  88.484911  
3              1       1        Kalwar Road,Jaipur  26.988300  75.584600  
4              1       1         Mai Mandir,Nadiad  22.700000  72.870000  
5              1       1       Elora Park,Vadodara  21.716412  73.004076  
6              1       1      Shirgaon,Maharashtra  19.032025  73.621535  
7              0       1          Anjurdive,Mumbai  18.966670  72.833330  
8              1       1       Rambaug,Maharashtra  19.243817  73.134692  
9              1       1  Borivali (West),Lalitpur  19.236100  72.833800

In [6]:
X_train=train.drop(columns="TARGET(PRICE_IN_LACS)")
y_train=train["TARGET(PRICE_IN_LACS)"]
print(X_train.shape)
print(y_train.shape)

(1213, 11)
(1213,)


In [7]:
miss_val=X_train.select_dtypes(include=["int64","float64"]).columns

In [8]:
X_train[miss_val].isnull().sum()

UNDER_CONSTRUCTION      10
RERA                    23
BHK_NO.                 94
SQUARE_FT             1077
READY_TO_MOVE           11
RESALE                   0
LONGITUDE              142
LATITUDE               146
dtype: int64

In [9]:
test[miss_val].isnull().sum()

UNDER_CONSTRUCTION    0
RERA                  0
BHK_NO.               0
SQUARE_FT             0
READY_TO_MOVE         0
RESALE                0
LONGITUDE             0
LATITUDE              0
dtype: int64

In [10]:
imputer_mean = SimpleImputer(strategy='mean')
#imputer_mean=SimpleImputer(strategy='constant',fill_value=99) if we want to input a value by your choise then ...

In [11]:
imputer_mean.fit(X_train[miss_val])

SimpleImputer()

In [12]:
imputer_mean.statistics_  #it gives us a statistic value of mean

array([1.79551122e-01, 3.08403361e-01, 2.37354781e+00, 1.62636057e+03,
       8.20299501e-01, 9.27452597e-01, 2.13237794e+01, 7.66613342e+01])

In [13]:
imputer_mean.transform(X_train[miss_val])

array([[ 0.      ,  0.      ,  2.      , ...,  1.      , 12.96991 ,
        77.59796 ],
       [ 0.      ,  0.      ,  2.      , ...,  1.      , 12.274538,
        76.644605],
       [ 0.      ,  0.      ,  2.      , ...,  1.      , 12.778033,
        77.632191],
       ...,
       [ 0.      ,  0.      ,  2.      , ...,  1.      , 13.05    ,
        80.11    ],
       [ 0.      ,  0.      ,  2.      , ...,  1.      , 21.167998,
        79.112474],
       [ 0.      ,  1.      ,  3.      , ...,  1.      , 12.86    ,
        77.786   ]])

In [14]:
X_train[miss_val]=imputer_mean.transform(X_train[miss_val])
#test[miss_val]=imputer_mean.transform(X_train[miss_val]) if there are any missing value in test data set but length be same

In [15]:
X_train[miss_val].isnull().sum()

UNDER_CONSTRUCTION    0
RERA                  0
BHK_NO.               0
SQUARE_FT             0
READY_TO_MOVE         0
RESALE                0
LONGITUDE             0
LATITUDE              0
dtype: int64

# Categorical Variable missing imputation

In [16]:
cat_val=X_train.select_dtypes(include=["O"]).columns
cat_val

Index(['POSTED_BY', 'BHK_OR_RK', 'ADDRESS'], dtype='object')

In [17]:
X_train[cat_val].isnull().sum()

POSTED_BY      0
BHK_OR_RK      0
ADDRESS      121
dtype: int64

In [18]:
imputer_mode = SimpleImputer(strategy='most_frequent')
imputer_mode

SimpleImputer(strategy='most_frequent')

In [19]:
imputer_mode.fit(X_train[cat_val])

SimpleImputer(strategy='most_frequent')

In [20]:
X_train[cat_val]=imputer_mode.transform(X_train[cat_val])

In [21]:
imputer_mode.statistics_

array(['Dealer', 'BHK', 'Zirakpur,Chandigarh'], dtype=object)

In [22]:
X_train[cat_val].isnull().sum()

POSTED_BY    0
BHK_OR_RK    0
ADDRESS      0
dtype: int64

In [23]:
X_train.head(50)

POSTED_BY  UNDER_CONSTRUCTION      RERA   BHK_NO. BHK_OR_RK     SQUARE_FT  \
0      Owner                 0.0  0.000000  2.000000       BHK   1300.236407   
1     Dealer                 0.0  0.000000  2.000000       BHK   1275.000000   
2      Owner                 0.0  0.000000  2.000000       BHK    933.159722   
3      Owner                 0.0  1.000000  2.000000       BHK    929.921143   
4     Dealer                 1.0  0.000000  2.000000       BHK    999.009247   
5      Owner                 0.0  0.000000  3.000000       BHK   1626.360571   
6     Dealer                 0.0  0.000000  3.000000       BHK   1495.053957   
7      Owner                 0.0  1.000000  3.000000       BHK   1181.012946   
8     Dealer                 0.0  1.000000  2.000000       BHK   1040.000000   
9      Owner                 0.0  1.000000  2.000000       BHK    879.120879   
10     Owner                 0.0  0.000000  3.000000       BHK   1350.308642   
11    Dealer                 0.0  0.000000  2.000000       BHK   1333.010179   
12     Owner                 0.0  0.000000  2.373548       BHK   1626.360571   
13     Owner                 0.0  1.000000  2.000000       BHK   1122.171946   
14     Owner                 0.0  0.000000  1.000000       BHK    649.983750   
15    Dealer                 1.0  1.000000  3.000000       BHK   1394.117647   
16     Owner                 0.0  0.000000  3.000000       BHK   1800.084710   
17    Dealer                 1.0  0.308403  3.000000       BHK   2124.896706   
18     Owner                 0.0  0.000000  2.000000       BHK   1100.000000   
19    Dealer                 0.0  1.000000  3.000000       BHK   2178.649237   
20     Owner                 0.0  0.000000  2.000000       BHK    881.143529   
21    Dealer                 0.0  0.000000  2.000000       BHK    944.881890   
22    Dealer                 0.0  1.000000  3.000000       BHK   1310.147689   
23    Dealer                 0.0  0.000000  1.000000       BHK    630.000630   
24    Dealer                 0.0  0.000000  2.000000       BHK   1219.809710   
25     Owner                 0.0  0.000000  2.000000       BHK   1626.360571   
26     Owner                 0.0  0.000000  2.373548       BHK   1600.000000   
27    Dealer                 0.0  0.000000  2.000000       BHK   1180.412371   
28     Owner                 1.0  0.000000  2.000000       BHK   1000.000000   
29    Dealer                 0.0  0.000000  2.000000       BHK   1000.000000   
30    Dealer                 0.0  0.000000  3.000000       BHK   1400.107701   
31    Dealer                 0.0  1.000000  2.000000       BHK    943.126608   
32     Owner                 0.0  0.000000  2.000000       BHK   1150.146382   
33    Dealer                 1.0  1.000000  1.000000       BHK    864.067439   
34    Dealer                 0.0  1.000000  2.000000       BHK    857.786197   
35     Owner                 0.0  0.000000  3.000000       BHK   1174.210077   
36    Dealer                 1.0  1.000000  2.373548       BHK   1020.087884   
37     Owner                 0.0  0.000000  2.373548       BHK   1650.165017   
38    Dealer                 1.0  0.000000  2.373548       BHK   1000.000000   
39     Owner                 0.0  0.000000  2.373548       BHK   1300.052002   
40    Dealer                 1.0  1.000000  2.373548       BHK  40606.195680   
41    Dealer                 0.0  1.000000  2.373548       BHK   1058.114928   
42    Dealer                 1.0  0.000000  2.373548       BHK    400.000000   
43    Dealer                 0.0  1.000000  2.373548       BHK   1274.924779   
44    Dealer                 0.0  0.000000  2.373548       BHK   1026.694045   
45     Owner                 0.0  0.000000  2.373548       BHK   1150.121065   
46     Owner                 0.0  0.000000  2.373548       BHK   1200.000000   
47    Dealer                 0.0  0.000000  2.373548        RK    475.010326   
48   Builder                 1.0  1.000000  2.373548       BHK    301.917116   
49 

# Data cleaning 
# diffrent statygy for diff variavbles

In [26]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [28]:
train=pd.read_csv(r"F:\ML_dataset\set_2\train.csv")
test=pd.read_csv(r"F:\ML_dataset\set_2\test.csv")
print(train.shape)
print(test.shape)

(1213, 12)
(1211, 11)


In [30]:
X_train=train.drop(columns="TARGET(PRICE_IN_LACS)")
y_train=train["TARGET(PRICE_IN_LACS)"]
X_test = test.copy()
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)

(1213, 11)
(1213,)
(1211, 11)


# missing value imputation

In [32]:
isnull_var = X_train.isnull().sum()
isnull_var

POSTED_BY                0
UNDER_CONSTRUCTION      10
RERA                    23
BHK_NO.                 94
BHK_OR_RK                0
SQUARE_FT             1077
READY_TO_MOVE           11
RESALE                   0
ADDRESS                121
LONGITUDE              142
LATITUDE               146
dtype: int64

In [35]:
miss_val=X_train.select_dtypes(include=["int64","float64"]).columns
num_val_miss = [var for var in miss_val if isnull_var[var]>0]
num_val_miss

['UNDER_CONSTRUCTION',
 'RERA',
 'BHK_NO.',
 'SQUARE_FT',
 'READY_TO_MOVE',
 'LONGITUDE',
 'LATITUDE']

In [37]:
cat_val=X_train.select_dtypes(include=["O"]).columns
cat_val_miss=[var for var in cat_val if isnull_var[var]>0]
cat_val_miss

['ADDRESS']

In [38]:
#mode value -- most frequent value

In [39]:
num_var_mean = ['BHK_NO.']
num_var_median = ['SQUARE_FT','LONGITUDE']
cat_var_mode = ['ADDRESS']
#num_ver_missing = ['UNDER_CONSTRUCTION','RERA','READY_TO_MOVE',]

In [45]:
num_var_mean_imputer = Pipeline(steps=[("inputer",SimpleImputer(strategy = "mean"))])
num_var_median_imputer = Pipeline(steps=[("inputer",SimpleImputer(strategy = "median"))])
cat_var_most_freq_imputer = Pipeline(steps=[("inputer",SimpleImputer(strategy = "most_frequent"))])
#num_var_missing_imputer = Pipeline(steps=[("inputer",SimpleImputer(strategy = "constant",fill_value = "missing"))])


In [48]:
prepocessor = ColumnTransformer (transformers=[("mean_imputer",num_var_mean_imputer,num_var_mean),("median_imputer",num_var_median_imputer,num_var_median),("mode_imputer",cat_var_most_freq_imputer,cat_var_mode)])
#,("missing_imputer",num_var_missing_imputer,num_ver_missing)

In [49]:
prepocessor.fit(X_train)

ColumnTransformer(transformers=[('mean_imputer',
                                 Pipeline(steps=[('inputer', SimpleImputer())]),
                                 ['BHK_NO.']),
                                ('median_imputer',
                                 Pipeline(steps=[('inputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['SQUARE_FT', 'LONGITUDE']),
                                ('mode_imputer',
                                 Pipeline(steps=[('inputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['ADDRESS'])])

In [57]:
prepocessor.named_transformers_["mean_imputer"].named_steps["inputer"].statistics_

array([2.37354781])

In [58]:
train['BHK_NO.'].mean()

2.3735478105451295

In [59]:
X_train_clear= prepocessor.transform(X_train)
X_test_clear= prepocessor.transform(X_test)

In [61]:
X_train_clear

array([[2.0, 1300.236407, 12.96991, 'Zirakpur,Chandigarh'],
       [2.0, 1275.0, 12.274538, 'Zirakpur,Chandigarh'],
       [2.0, 933.1597222, 12.778033, 'Zirakpur,Chandigarh'],
       ...,
       [2.0, 1150.14121, 13.05, 'Poonamallee,Chennai'],
       [2.0, 1150.14121, 21.167998, 'Vaishali Nagar,Nagpur'],
       [3.0, 1150.14121, 12.86, 'Sarjapur Road,Bangalore']], dtype=object)

In [62]:
prepocessor.transformers_    

[('mean_imputer', Pipeline(steps=[('inputer', SimpleImputer())]), ['BHK_NO.']),
 ('median_imputer',
  Pipeline(steps=[('inputer', SimpleImputer(strategy='median'))]),
  ['SQUARE_FT', 'LONGITUDE']),
 ('mode_imputer',
  Pipeline(steps=[('inputer', SimpleImputer(strategy='most_frequent'))]),
  ['ADDRESS']),
 ('remainder', 'drop', [0, 1, 2, 4, 6, 7, 10])]